development:
  adapter: postgresql
  encoding: unicode
  database: my_rails_app
  pool: 5
  username: richardcox
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_rails_app
  pool: 5
  username: richardcox
  password: